### ISSUE TITLE
default config `Pulumi.localstack.yaml` causes ` * : invalid or unknown key` error

### ISSUE THREAD

**Issue by chrisfentiman** [localstack/pulumi-local#8]
It appears that the list of endpoints initially seeded by `pulumilocal init` is now causing deployment errors with Pulumilocal. (It took me forever to figure out what was going on.)

### Checklist to ensure I'm not crazy:

- [x] Verified AWS is not called by any API
- [x] Verified Localstack docker is not called by any API
- [x] Removed all dependencies and had a clean install
- [x] Ensure no modification to the initial config file.
- [x] Verified it is not any of the following issues:
  -  [Pulumi/Pulumi - Issue: could not validate provider configuration: 2 errors occurred ](https://github.com/pulumi/pulumi/issues/4718)
  - [Pulumi/Pulumi - Issue: Could not validate provider configuration occurs when project == provider](https://github.com/pulumi/pulumi/issues/3546)
- [x] Confirmed removing `aws:endpoints` and reverting pr #2  works _(within reason - I still needed to add back in a bunch of endpoints to get the final deployment because the initial list is missing required endpoints - I have not settled on the exact service that is causing the issue, hoping you have some neat way to parse all of the services quickly and compare.)_

### Step to reproduce: 

Pre-requisites: 
- Pulumi-local version: `0.40`
- Pulumi CLI version: `3.47.1`
- New project.

Run the normal `pulumilocal init` -- the new `Pulumi.localstack.yaml` file includes all the endpoints and other configs set by `pulumilocal`

```
.
├── infra/
│   ├── Pulumi.yaml
│   ├── Pulumi.prod.yaml
│   └── Pulumi.localstack.yaml <- new!
└── src/
    └── some-code.lang

```

Make no modifications at all to `Pulumi.localstack.yaml` and run `pulumilocal up -s localstack`

Assuming you go through the whole "setup process" for the final output, you'll eventually hit an error, as shown below.

```bash
Diagnostics:
  aws:cloudwatch:LogGroup (package-ecs-task-definition):
    error: could not validate provider configuration: 1 error occurred:
        * Invalid or unknown key

  pulumi:pulumi:Stack (package-local):
    warning: provider config warning: Use s3_use_path_style instead.
    error: Error: invocation of aws:ec2/getVpc:getVpc returned an error: could not validate provider configuration: 1 error occurred:
        * Invalid or unknown key
    
    
        at Object.callback (/Users/normal/path/to/node_modules/@pulumi/runtime/invoke.ts:159:33)
        at Object.onReceiveStatus (/Users/normal/path/to/node_modules/@grpc/grpc-js/src/client.ts:338:26)
        at Object.onReceiveStatus (/Users/normal/path/to/node_modules/@grpc/grpc-js/src/client-interceptors.ts:426:34)
        at Object.onReceiveStatus (/Users/normal/path/to/node_modules/@grpc/grpc-js/src/client-interceptors.ts:389:48)
        at /Users/normal/path/to/node_modules/@grpc/grpc-js/src/call-stream.ts:276:24
        at processTicksAndRejections (node:internal/process/task_queues:78:11)
    error: Error: invocation of aws:index/getAvailabilityZones:getAvailabilityZones returned an error: could not validate provider configuration: 1 error occurred:
        * Invalid or unknown key
    
    
        at Object.callback (/Users/normal/path/to/node_modules/@pulumi/runtime/invoke.ts:159:33)
        at Object.onReceiveStatus (/Users/normal/path/to/node_modules/@grpc/grpc-js/src/client.ts:338:26)
        at Object.onReceiveStatus (/Users/normal/path/to/node_modules/@grpc/grpc-js/src/client-interceptors.ts:426:34)
        at Object.onReceiveStatus (/Users/normal/path/to/node_modules/@grpc/grpc-js/src/client-interceptors.ts:389:48)
        at /Users/normal/path/to/node_modules/@grpc/grpc-js/src/call-stream.ts:276:24
        at processTicksAndRejections (node:internal/process/task_queues:78:11)
    error: Error: invocation of aws:iam/getPolicyDocument:getPolicyDocument returned an error: could not validate provider configuration: 1 error occurred:
        * Invalid or unknown key
    
    
        at Object.callback (/Users/normal/path/to/node_modules/@pulumi/runtime/invoke.ts:159:33)
        at Object.onReceiveStatus (/Users/normal/path/to/node_modules/@grpc/grpc-js/src/client.ts:338:26)
        at Object.onReceiveStatus (/Users/normal/path/to/node_modules/@grpc/grpc-js/src/client-interceptors.ts:426:34)
        at Object.onReceiveStatus (/Users/normal/path/to/node_modules/@grpc/grpc-js/src/client-interceptors.ts:389:48)
        at /Users/normal/path/to/node_modules/@grpc/grpc-js/src/call-stream.ts:276:24
        at processTicksAndRejections (node:internal/process/task_queues:78:11)
    error: Error: invocation of aws:iam/getPolicyDocument:getPolicyDocument returned an error: could not validate provider configuration: 1 error occurred:
        * Invalid or unknown key
    
    
        at Object.callback (/Users/normal/path/to/node_modules/@pulumi/runtime/invoke.ts:159:33)
        at Object.onReceiveStatus (/Users/normal/path/to/node_modules/@grpc/grpc-js/src/client.ts:338:26)
        at Object.onReceiveStatus (/Users/normal/path/to/node_modules/@grpc/grpc-js/src/client-interceptors.ts:426:34)
        at Object.onReceiveStatus (/Users/normal/path/to/node_modules/@grpc/grpc-js/src/client-interceptors.ts:389:48)
        at /Users/normal/path/to/node_modules/@grpc/grpc-js/src/call-stream.ts:276:24
        at processTicksAndRejections (node:internal/process/task_queues:78:11)
```

**Comment by chrisfentiman** [comment]
Read the other issues here - looks great! #5 

- next time, I'm starting there.
